name: build

on:
  workflow_dispatch:
  push:

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPO: 912455136424.dkr.ecr.us-east-2.amazonaws.com/terraform-aws-alert
  ECR_POLICY: '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "production-access",
                "Effect": "Allow",
                "Principal": {
                  "Service": [
                    "ec2.amazonaws.com",
                    "lambda.amazonaws.com"
                  ],
                  "AWS": [
                    "arn:aws:iam::503954333251:root"
                  ]
                },
                "Action": [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:BatchGetImage",
                  "ecr:DescribeImages",
                  "ecr:DescribeRepositories",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:GetLifecyclePolicy",
                  "ecr:GetLifecyclePolicyPreview",
                  "ecr:GetRepositoryPolicy",
                  "ecr:ListImages"
                ]
              },
              {
                "Sid": "org-access",
                "Effect": "Allow",
                "Principal": {
                  "AWS": "*"
                },
                "Action": [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:BatchGetImage",
                  "ecr:DescribeImages",
                  "ecr:DescribeRepositories",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:GetLifecyclePolicy",
                  "ecr:GetLifecyclePolicyPreview",
                  "ecr:GetRepositoryPolicy",
                  "ecr:ListImages"
                ],
                "Condition": {
                  "ForAnyValue:StringLike": {
                    "aws:PrincipalOrgPaths": "o-685w7eamma/*"
                  }
                }
              }
            ]
          }'

defaults:
  run:
    shell: bash

jobs:
  ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker build
        run: docker build -t ${REPO}:${GITHUB_SHA} .
      - name: ecr login
        run: aws ecr --region us-east-2 get-login-password | docker login --username AWS --password-stdin 912455136424.dkr.ecr.us-east-2.amazonaws.com
      - name: Create ECR Repos
        run: |
          aws ecr create-repository --region "$AWS_DEFAULT_REGION" --repository-name terraform-aws-alert || echo "repo already exists"
          aws ecr set-repository-policy --region "$AWS_DEFAULT_REGION" --repository-name terraform-aws-alert --policy-text "$ECR_POLICY"
      - name: docker push
        run: docker push ${REPO}:${GITHUB_SHA}
