name: jira

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - uses: champ-oss/jira-notification@develop
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          JIRA_REPO: terraform-aws-alert
          JIRA_PROJECT: CTEST
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
